### PR TITLE
Fix warnings from Ruby 2.7

### PR DESCRIPTION
**Pull request by AlexWayfer**
Add specs for it.

### CODE REVIEW

**Comment by AlexWayfer** [comment]
And cache, cache is depending on `args` and it's wrong now. I'll add tests.

**Comment by AlexWayfer** [comment]
> Looks like it fails in older rubies.

Done. It's strange, I didn't find anything related in Ruby 2.5.0 changes.

> And cache, cache is depending on args and it's wrong now. I'll add tests.

Done.

**Comment by tycooon** [comment]
> Done. It's strange, I didn't find anything related in Ruby 2.5.0 changes.
AFAIR there were some bugfixes in handling kwargs.

**Comment by tycooon** [comment]
Now rubocop is unhappy though :(

**Comment by AlexWayfer** [comment]
> Now rubocop is unhappy though :(

Oh, not a problem. I'm used to 80-symbols lines or not limit at all. Didn't notice offenses, sorry.

**Comment by AlexWayfer** [comment]
And it's hard to test:

```
> bundle exec rubocop 
Error: The `Naming/UncommunicativeMethodParamName` cop has been renamed to `Naming/MethodParameterName`.
(obsolete configuration found in .rubocop.yml, please update it)
```

:grimacing:

**Comment by AlexWayfer** [comment]
> private method `define_method' called (Ruby 2.4)

Okay then!

**Comment by AlexWayfer** [comment]
And the problem with:

> This branch is out-of-date with the base branch

because of https://github.com/tycooon/memery/commit/ff64398e557c74a6797ea93733dd37d39d38e48c#commitcomment-36941780

**Comment by tycooon** [comment]
Thanks for the patch!

**Pull request merged**
