### PR TITLE
Allow to `extend Memery`

### PR DESCRIPTION
**Pull request by AlexWayfer**
I think there is nothing wrong here.

### CODE REVIEW

**Comment by tycooon** [comment]
I don't like it a lot, because `extend` is not supposed to add instance level methods I think (and Memery does add `clear_memery_cache!`), while `include` adding both instance- and class- methods is a common practice.

**Comment by AlexWayfer** [comment]
> while include adding both instance- and class- methods is a common practice.

But how?!

**Comment by AlexWayfer** [comment]
> For example ActiveSupport::Concern works like this.

Oh, it's Rails practice, not Ruby, I think.

**Comment by tycooon** [comment]
Well, this might make migrating from memoist easier, but imagine if you are working on a project and you see `include Memery` in one place and `extend Memery` in another one. I think this is confusing and just doesn't feel right.

**Comment by AlexWayfer** [comment]
> but imagine if you are working on a project and you see include Memery in one place and extend Memery in another one. I think this is confusing and just doesn't feel right.

1. I think, there is should be convention in one project, like about indentation or blocks. Imagine you're working on a project and you see indentation with tabs in one place and indentation with spaces in another. :slightly_smiling_face: 
2. I insist on `extend`, because the main method of `Memery` is `.memoize`, not `#clear_memery_cache!`

**Comment by tycooon** [comment]
Sorry, but I prefer `include` and allowing both means introducing ambiguity that I would like to avoid.

**Pull request closed without merging**
